server:
  port: 9991

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.76.51.38:9901/eureka/

zuul:
  routes:
    api:
      path: /api/**
      serviceId: service-export
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000

spring:
  application:
    name: service-zuul